### ISSUE TITLE
Use icons/graphics instead of text to save space on the screen

### ISSUE THREAD

**Issue by Vag3d** [GullCode/portapack-mayhem#2]
**Is your feature request related to a problem? Please describe.**

Every app have settings that we set to work the way we want.
i.e. LNA, VGA AMP, VOL, SQUELCH, WAIT, etc.
Those text words of each one, some times occupy valuable space on the screen leaving no space on the screen for other features we want or for showing something we want, even bigger.

**Describe the solution you'd like**

We could create "icons" to replace some texts (commonly) used in the apps, to save pixels on the screen and have more space for various new features (that may not fit now).

The icons should occupy less space than the text used until now.
We should prioritize the replacement of common used texts first (like i.e. LNA, VGA AMP, VOL, SQUELCH, WAIT, etc.) so they can be used in every app if the creators of each app want.

The icons should not make it more difficult for the user to understand what is each setting. It should be as "self explaining" as possible. (or for more difficult icons we could have an explaining help file both in wiki or inside the firmware somehow)

We know that the specifications of the icons are 16x16pixels, monochrome (1bit).

Here are some icons I created so you can check them and test them if you like them and see if they can help somehow to accomplish the goal.

I don't know how to put them on github. Should I create a pull request? So I put them in my dropbox.

https://www.dropbox.com/sh/okqopdr42kow584/AACxVt0S9b9U6Z3VM_3mBAaHa?dl=0

hint and tip: For some special icons that needs to be bigger than 16x16pixels, we could stick two or more icons together (the one next to each other) to form / create a bigger one. ;-)

Best regards

Vag3d

**Comment by Vag3d** [comment]
I added more icons for the apps.
I have different approaches (versions) for some icons.

icon_-f.png
icon_+f.png
icon_addf.png
icon_f-.png
icon_f-2.png
icon_f+.png
icon_f+2.png
icon_m-.png
icon_m-2.png
icon_m+.png
icon_m+2.png
icon_m1.png
icon_remf.png
icon_rst.png

**Comment by GullCode** [comment]
Thanks for the ideas. I may use some of them, do not delete the dropbox yet :-D

**Comment by GullCode** [comment]
I have to concentrate on finishing freqman gui for proper edition, and I think i will go on a couple of show/hides menu buttons instead of bitmaps.
Thanks for trying :-)
