### ISSUE TITLE
Freqman ranges steps, Hamradio

### ISSUE THREAD

**Issue by GullCode** [GullCode/portapack-mayhem#3]
-When using ranges, the step is not one by range bu the one selected in the UI before loading the input file
-No support for entries like rx=freq,tx=freq,desc=desc:tone=tonevalue

Solutions:
-Add custom steps on range, allow default behavior if no range given
-Add a HAMRADIO type entry in freqman, supporting  rx=freq,tx=freq,desc=desc:tone=tonevalue
tone is mixed in description with a separator that is not ','
-See if Mic TX can already take predefined tone at app launching, else allow it

Additional solution:
-For HAMRADIO one can already make frequencies only lists, with one entry for rx, one entry for tx and tone in the description

**Comment by Vag3d** [comment]
Don't forget the "skip" option.
It is useful for some situations on ham radio, i.e. skip the repeater (on/off) without having to delete it from the list.

I putted the file "REPEATERS_GR4.txt" I prepared once, to the dropbox link I gave you on my other post for the icons, so you can have something to test if you find it useful.

Dropbox link:
https://www.dropbox.com/sh/okqopdr42kow584/AACxVt0S9b9U6Z3VM_3mBAaHa?dl=0

it have the repeaters list I created by gathering from various sources in the internet its names and frequencies. I have it in the following format to help you:
Rx=Receiving Frequency.
Tx=Transmitting Frequency
Tone=CTSS Tone
Mod = Modulation (AM, AM/USB, AM/LSB, FM/WFM, FM/NFM, CW, etc)
Skip = If Yes, the scan should skip this preset and not scan it. (for broken repeaters, for digital repeaters that are hearing like noise if you are analog, for repeaters like weather stations that emitting 24/7/365, etc)
Desc = Description

Example: 

Rx=14575000,Tx=14515000,tone=88500000,mod=FM,skip=no,desc=SV2A


Those could be applied to the Mic TX app too so when we use it it should be able to load those files too.
Also Mic Tx should have a multi-CTCSS option (an option of the many that exists for CTCSS codes, to play them all the one after another quickly,  so "every" repeater should open, without having to guess or try and error to find the correct one)

Best regards. ;-)

Vag3d

**Comment by GullCode** [comment]
Thanks for the list :+1: 
For the skip thing I didn't think it had to be part of the list. Let's say I'm skipping one. If it's saved in the file it will never be displayed anymore, so how would I unskip it ? Special menu ? Or freq manager upgrade to allow unskip ?
I was more thinking of a temporary skip, like you load your file, you search, at some point you want to skip one, then it's removed but only from the loaded list, and not from the file. Reloading the file would reset the skipped stations.
Think about it and tell me :-)
Can you also check this file and tell me if all tones code are here or if others are needed: 
And yes, in case of emergency it can be helpful to play them all. We may have to test to see if it works.

**Comment by GullCode** [comment]
Search app and freqman funcs are now able to load modulation / bandwidth / step / tone.
